name: CI
# thanks for @mpariente for copying this workflow
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  src-test:
    name: conda-tests
    runs-on: ubuntu-latest

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: umx-cpu
          environment-file: scripts/environment-cpu-linux.yml
          auto-update-conda: true
          auto-activate-base: false
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -e .['tests']
          python --version
          pip --version
          python -m pip list
      - name: Conda list
        run: conda list
      - name: Create dummy dataset
        run: |
          conda install -c conda-forge sox 
          chmod +x tests/create_dummy_datasets.sh
          ./tests/create_dummy_datasets.sh
        shell: bash

      - name: Source code tests
        run: |
          py.test tests/test_regression.py -v